Repository deltachat/deltachat-desktop, pull requests merged in 2019-06, with the labels that each got.

#828 fix: use a friendlier file name for logs on windows (: not appreciated)
  src/main/log-handler.js
Labels: bug

#855 Cleanup styles
  README.md
  README_ASSETS/devMenu.png
  README_ASSETS/screenshot.png
  images/android.svg
  images/apple.svg
  images/appstore.svg
  images/broken-link.svg
  images/gear.svg
  images/playstore.png
  images/timer-00.svg
  images/timer-05.svg
  images/timer-10.svg
  images/timer-15.svg
  images/timer-20.svg
  images/timer-25.svg
  images/timer-30.svg
  images/timer-35.svg
  images/timer-40.svg
  images/timer-45.svg
  images/timer-50.svg
  images/timer-55.svg
  images/timer-60.svg
  images/timer-disabled.svg
  images/timer.svg
  scss/_debugLog.scss
  scss/_emoji.scss
  scss/_global.scss
  scss/_lightbox.scss
  scss/_modal.scss
  scss/_options.scss
  scss/_progress.scss
  scss/_settings.scss
  scss/manifest.scss
  scss/modules/_conversation-header.scss
  scss/modules/_expire-timer.scss
  scss/modules/_notification.scss
  scss/modules/index.scss
  src/renderer/components/conversations/ExpireTimer.js
  src/renderer/components/conversations/Message.js
  src/renderer/components/conversations/MessageMetaData.js
Labels: maintenance

#860 re-add test for mising translations script
  bin/test_for_missing_translations.sh
Labels: maintenance, translations
