Repository deltachat/deltachat-desktop, pull requests merged in 2020-11, with the labels that each got.

#1960 Update translations for new core strings
  src/main/deltachat/login.ts
Labels: maintenance, translations

#1957 Remove failed-to-configure accounts
  CHANGELOG.md
  src/main/deltachat/login.ts
  src/main/logins.ts
Labels: bug

#1962 Implement check for unused variables
  package-lock.json
  package.json
  src/main/deltachat/autocrypt.ts
  src/main/deltachat/burnerAccounts.ts
  src/main/deltachat/chatlist.ts
  src/main/deltachat/controller.ts
  src/main/index.ts
  src/main/ipc.ts
  src/main/tsconfig.json
  src/main/windows/call.ts
  src/main/windows/help.ts
  src/main/windows/main.ts
  src/renderer/App.tsx
  src/renderer/ScreenController.tsx
  src/renderer/components/LoginForm.tsx
  src/renderer/components/LoginScreen.tsx
  src/renderer/components/OfflineToast.tsx
  src/renderer/components/attachment/mediaAttachment.tsx
  src/renderer/components/attachment/messageAttachment.tsx
  src/renderer/components/chat/ChatList.tsx
  src/renderer/components/composer/ComposerMessageInput.tsx
  src/renderer/components/dialogs/ConfirmationDialog.tsx
  src/renderer/components/dialogs/DeltaDialog.tsx
  src/renderer/components/dialogs/DialogController.tsx
  src/renderer/components/dialogs/EditGroup.tsx
  src/renderer/components/dialogs/EncryptionInfo.tsx
  src/renderer/components/dialogs/EnterAutocryptSetupMessage.tsx
  src/renderer/components/dialogs/ImportQrCode.tsx
  src/renderer/components/dialogs/MessageDetail.tsx
  src/renderer/components/dialogs/MuteChat.tsx
  src/renderer/components/dialogs/QrCode.tsx
  src/renderer/components/dialogs/Settings-Account.tsx
  src/renderer/components/dialogs/Settings-Appearance.tsx
  src/renderer/components/dialogs/Settings-Autodelete.tsx
  src/renderer/components/dialogs/Settings-Encryption.tsx
  src/renderer/components/dialogs/Settings-ManageKeys.tsx
  src/renderer/components/dialogs/Settings.tsx
  src/renderer/components/dialogs/ViewProfile.tsx
  src/renderer/components/helpers/ChatMethods.ts
  src/renderer/components/helpers/OpenQrUrl.tsx
  src/renderer/components/message/Message.tsx
  src/renderer/components/message/MessageMarkdown.tsx
  src/renderer/components/message/MessageWrapper.tsx
  src/renderer/contexts.ts
  src/renderer/delta-remote.ts
  src/renderer/ipc.ts
  src/renderer/runtime.ts
  src/renderer/stores/chat.ts
  src/renderer/stores/contacts.ts
  src/renderer/stores/locations.ts
  src/renderer/tsconfig.json
  src/shared/tsconfig.json
Labels: maintenance

#1951 Implement draft message with attachment & reply to message
  CHANGELOG.md
  scss/composer/_composer.scss
  scss/gallery/_attachment-view.scss
  scss/message/_message-list.scss
  scss/message/_message.scss
  src/main/deltachat/chatlist.ts
  src/main/deltachat/messagelist.ts
  src/renderer/components/attachment/messageAttachment.tsx
  src/renderer/components/composer/Composer.tsx
  src/renderer/components/composer/ComposerMessageInput.tsx
  src/renderer/components/map/MapComponent.tsx
  src/renderer/components/message/Message.tsx
  src/renderer/components/message/MessageListAndComposer.tsx
  src/renderer/components/message/messageFunctions.ts
  src/renderer/delta-remote.ts
  src/renderer/global.d.ts
  src/renderer/stores/chat.ts
  src/shared/shared-types.d.ts
  themes/_themebase.scss
Labels: enhancement

#1906 Implement tray icon
  CHANGELOG.md
  _locales/_untranslated_en.json
  images/trayIconTemplate.png
  images/trayIconTemplate@2x.png
  src/main/application-constants.ts
  src/main/deltachat/settings.ts
  src/main/index.ts
  src/main/tray.ts
  src/renderer/components/dialogs/Settings.tsx
  src/shared/shared-types.d.ts
  src/shared/state.ts
Labels: enhancement
