Repository deltachat/deltachat-desktop, pull requests merged in 2024-10, with the labels that each got.

#4173 perf: cache chat list & don't delay initial load
  CHANGELOG.md
  packages/frontend/src/components/chat/ChatList.tsx
  packages/frontend/src/components/chat/ChatListHelpers.tsx
Labels: performance

#4170 fix running with local core
  bin/link_core/link_local.sh
Labels: bug

#4178 improvement: better search for invite link
  CHANGELOG.md
  _locales/_untranslated_en.json
  packages/frontend/src/components/helpers/PseudoListItem.tsx
Labels: ui/ux

#4207 refactor: improve `jumpToMessage` docstring
  packages/frontend/src/stores/messagelist.ts
Labels: refactor

#4206 perf: make `jumpToMessage` a tiny bit faster
  CHANGELOG.md
  packages/frontend/src/components/attachment/mediaAttachment.tsx
  packages/frontend/src/components/composer/Composer.tsx
  packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx
  packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx
  packages/frontend/src/components/dialogs/ForwardMessage/index.tsx
  packages/frontend/src/components/dialogs/FullscreenMedia.tsx
  packages/frontend/src/components/message/Message.tsx
  packages/frontend/src/hooks/chat/useMessage.ts
  packages/frontend/src/hooks/useVideoChat.ts
Labels: performance

#4236 fix: emoji picker: Shift + click not working
  packages/frontend/src/components/composer/Composer.tsx
Labels: bug

#4229 refactor: remove unused SCSS
  packages/frontend/scss/message/_message-detail.scss
Labels: refactor

#4227 fix: don't overflow gallery tabs on narrow screen
  packages/frontend/scss/gallery/_media.scss
Labels: bug, ui/ux, polish

#4247 fix: image thumbnails not showing in chat list
  CHANGELOG.md
  packages/frontend/src/components/chat/ChatListItem.tsx
Labels: bug

#4253 style: avoid horizontal scrollbars in chat list
  CHANGELOG.md
  packages/frontend/scss/chat/_chat-list-item.scss
  packages/frontend/scss/contact/_contact.scss
Labels: bug

#4257 refactor: remove some unused SCSS
  packages/frontend/scss/_variables.scss
  packages/frontend/scss/dialogs/_autocrypt_setup.scss
  packages/frontend/scss/dialogs/_ephermeral_message.scss
  packages/frontend/scss/dialogs/_group-styles.scss
  packages/frontend/scss/dialogs/_qr-import.scss
  packages/frontend/scss/dialogs/_settings.scss
  packages/frontend/scss/dialogs/multidevice/send_backup.scss
  packages/frontend/scss/manifest.scss
Labels: refactor

#4255 style: fix VCard color in dark theme
  CHANGELOG.md
  packages/frontend/src/components/message/styles.module.scss
Labels: polish

#4254 fix: horizontal scrollbar in "View Group"
  CHANGELOG.md
  packages/frontend/src/components/dialogs/ViewGroup.tsx
Labels: bug, ui/ux

#4299 style: fix avatar in profile being oval-shaped
  CHANGELOG.md
  packages/frontend/src/components/Avatar/styles.module.scss
  packages/frontend/src/components/ProfileInfoHeader/styles.module.scss
Labels: ui/ux
