Repository deltachat/deltachat-desktop, pull requests merged in 2024-12, with the labels that each got.

#4380 New webxdc api
  packages/frontend/src/components/attachment/mediaAttachment.tsx
  packages/frontend/src/components/message/Message.tsx
  packages/frontend/src/components/message/messageFunctions.ts
  packages/frontend/src/system-integration/webxdc.ts
  packages/shared/shared-types.d.ts
  packages/target-electron/src/deltachat/webxdc.ts
  packages/target-electron/static/webxdc-preload.js
Labels: wait-for-core

#4280 account list events and private tags
  CHANGELOG.md
  images/icons/sell.svg
  packages/frontend/src/components/AccountListSidebar/AccountHoverInfo.tsx
  packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
  packages/frontend/src/components/AccountListSidebar/AccountListSidebar.tsx
  packages/frontend/src/components/AccountListSidebar/EditPrivateTagDialog.tsx
  packages/frontend/src/components/Icon/index.tsx
  packages/frontend/src/components/dialogs/SetupMultiDevice/ReceiveBackupProgressDialog.tsx
  packages/frontend/src/components/screens/AccountSetupScreen.tsx
  packages/frontend/src/hooks/useInstantOnboarding.ts
  packages/frontend/src/stores/settings.ts
Labels: bug, enhancement, refactor

#4385 fullscreen media view: improve drag behaviour and remove visible scrollbars
  CHANGELOG.md
  packages/frontend/scss/gallery/_attachment-view.scss
  packages/frontend/src/components/dialogs/FullscreenMedia.tsx
Labels: bug

#3958 upgrade react to v18 and react pinch pan to v3
  CHANGELOG.md
  packages/frontend/package.json
  packages/frontend/src/components/Gallery.tsx
  packages/frontend/src/components/composer/Composer.tsx
  packages/frontend/src/components/composer/ComposerMessageInput.tsx
  packages/frontend/src/components/screens/CrashScreen.tsx
  packages/frontend/src/components/screens/RecoverableCrashScreen.tsx
  packages/frontend/src/contexts/ContextMenuContext.tsx
  packages/frontend/src/main.tsx
  pnpm-lock.yaml
Labels: technical debt
