Repository deltachat/deltachat-desktop, pull requests merged in 2024-02, with the labels that each got.

#3654 Indicate better that some info bubbles are interactive
  scss/message/_message.scss
  src/renderer/components/message/Message.tsx
Labels: ui/ux

#3650 Copy invite link to clipboard instead of only QR code data
  CHANGELOG.md
  src/renderer/components/dialogs/QrCode.tsx
  src/renderer/utils/invite.ts
Labels: ui/ux, new-core

#3652 Show info dialog on tap for invalid unencrypted mails
  CHANGELOG.md
  _locales/bg.xml
  _locales/ca.xml
  _locales/ckb.xml
  _locales/cs.xml
  _locales/da.xml
  _locales/de.xml
  _locales/el.xml
  _locales/en.xml
  _locales/eo.xml
  _locales/es.xml
  _locales/eu.xml
  _locales/fa.xml
  _locales/fi.xml
  _locales/fr.xml
  _locales/gl.xml
  _locales/id.xml
  _locales/it.xml
  _locales/ja_JP.xml
  _locales/km.xml
  _locales/ko.xml
  _locales/nb.xml
  _locales/nl_NL.xml
  _locales/pl.xml
  _locales/pt_BR.xml
  _locales/ro.xml
  _locales/ru.xml
  _locales/sc.xml
  _locales/sk.xml
  _locales/sq.xml
  _locales/sr.xml
  _locales/sv.xml
  _locales/tr.xml
  _locales/uk.xml
  _locales/vi.xml
  _locales/zh_CN.xml
  _locales/zh_TW.xml
  scss/message/_message.scss
  src/renderer/components/dialogs/InvalidUnencryptedMail.tsx
  src/renderer/components/message/Message.tsx
  src/renderer/stockStrings.ts
Labels: ui/ux, new-core

#3639 Do not add changelog device message on fresh accounts
  CHANGELOG.md
  src/renderer/ScreenController.tsx
  src/renderer/deviceMessages.ts
Labels: ui/ux, wait-for-core, new-core

#3672 make sidebar menu obsolete
  images/icons/info.svg
  images/icons/question_mark.svg
  src/renderer/components/Icon/index.tsx
  src/renderer/components/Settings/ChatsAndMedia.tsx
  src/renderer/components/Settings/Settings.tsx
  src/renderer/components/Sidebar.tsx
Labels: enhancement, ui/ux

#3621 Account Sidebar
  CHANGELOG.md
  _locales/_untranslated_en.json
  bin/build-frontend-ts.mjs
  docs/THEMES.md
  images/account_deletion_background.jpg
  images/icons/settings.svg
  scss/_account-list.scss
  scss/_connectivity-toast.scss
  scss/_global.scss
  scss/_sidebar.scss
  scss/_variables.scss
  scss/chat/_chat-list-item.scss
  scss/chat/_chat-list.scss
  scss/gallery/_media.scss
  scss/login/_login.scss
  scss/main_screen/_main_screen.scss
  scss/main_screen/_navbar_wrapper.scss
  scss/manifest.scss
  scss/map/_map.scss
  scss/message/_message-list.scss
  scss/overwrites/_bp4-overwrites.scss
  src/main/ipc.ts
  src/main/windows/main.ts
  src/renderer/ScreenController.tsx
  src/renderer/backend-com.ts
  src/renderer/components/AccountListSidebar/AccountHoverInfo.tsx
  src/renderer/components/AccountListSidebar/AccountItem.tsx
  src/renderer/components/AccountListSidebar/AccountListSidebar.tsx
  src/renderer/components/AccountListSidebar/styles.module.scss
  src/renderer/components/Icon/index.tsx
  src/renderer/components/SearchInput/SearchInputButton.tsx
  src/renderer/components/SearchInput/styles.module.scss
  src/renderer/components/Settings/ExperimentalFeatures.tsx
  src/renderer/components/Sidebar.tsx
  src/renderer/components/ThreeDotMenu.tsx
  src/renderer/components/chat/ChatList.tsx
  src/renderer/components/dialogs/About.tsx
  src/renderer/components/dialogs/SetupMultiDevice/ReceiveBackupDialog.tsx
  src/renderer/components/helpers/OpenQrUrl.tsx
  src/renderer/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx
  src/renderer/components/screens/AccountDeletionScreen/styles.module.scss
  src/renderer/components/screens/AccountListScreen.tsx
  src/renderer/components/screens/AccountSetupScreen.tsx
  src/renderer/components/screens/MainScreen.tsx
  src/renderer/components/screens/NoAccountSelectedScreen/NoAccountSelectedScreen.tsx
  src/renderer/components/screens/NoAccountSelectedScreen/styles.module.scss
  src/renderer/components/screens/WelcomeScreen.tsx
  src/renderer/global.d.ts
  src/renderer/stores/settings.ts
  src/renderer/system-integration/badge-counter.ts
  src/shared/shared-types.d.ts
  themes/_themebase.scss
  themes/dark.scss
  themes/dark_amoled.scss
  themes/darkpurple.scss
  themes/dev_minimal.scss
  themes/dev_rocket.scss
  themes/light.scss
Labels: enhancement

#3680 Multi Account Notifications
  CHANGELOG.md
  _locales/_untranslated_en.json
  bin/build-frontend-ts.mjs
  images/icons/audio-muted.svg
  scss/_mixins.scss
  src/renderer/components/AccountListSidebar/AccountHoverInfo.tsx
  src/renderer/components/AccountListSidebar/AccountItem.tsx
  src/renderer/components/AccountListSidebar/AccountListSidebar.tsx
  src/renderer/components/AccountListSidebar/styles.module.scss
  src/renderer/components/Icon/index.tsx
  src/renderer/components/Settings/Notifications.tsx
  src/renderer/components/screens/AccountDeletionScreen/AccountDeletionScreen.tsx
  src/renderer/components/screens/AccountDeletionScreen/styles.module.scss
  src/renderer/global.d.ts
  src/renderer/stores/accountNotifications.ts
  src/renderer/system-integration/badge-counter.ts
  src/renderer/system-integration/notifications.ts
Labels: enhancement

#3691 Fix broken/wrong/missing background for muted and turned off account badges in multiaccount sidebar
  CHANGELOG.md
  src/renderer/components/AccountListSidebar/AccountItem.tsx
  src/renderer/components/AccountListSidebar/styles.module.scss
Labels: bug

#3605 Refactor buttons
  CHANGELOG.md
  scss/manifest.scss
  scss/misc/_delta-buttons.scss
  src/renderer/components/Button/index.tsx
  src/renderer/components/Button/style.module.scss
  src/renderer/components/Dialog/FooterActionButton.tsx
  src/renderer/components/Dialog/styles.module.scss
  src/renderer/components/composer/EmojiAndStickerPicker.tsx
  src/renderer/components/dialogs/About.tsx
  src/renderer/components/dialogs/ViewGroup.tsx
  src/renderer/components/dialogs/ViewProfile/index.tsx
  src/renderer/components/message/Message.tsx
  src/renderer/components/screens/WelcomeScreen.tsx
Labels: refactor

#3704 fix broken html email window (CSP got broken with the recent electron update)
  CHANGELOG.md
  src/main/windows/html_email.ts
Labels: bug, blocker
