Repository deltachat/deltachat-desktop, pull requests merged in 2024-07, with the labels that each got.

#3984 feat: more shortcuts to switch between chats
  CHANGELOG.md
  docs/KEYBINDINGS.md
  src/renderer/components/KeyboardShortcutHint.tsx
  src/renderer/keybindings.ts
Labels: enhancement, ui/ux, accessibility

#3993 refactor: safer types
  CHANGELOG.md
  src/renderer/stores/settings.ts
Labels: refactor

#4000 refactor into proper function components, otherwise we would not be allowed to use hooks in those functions if they just return JSX without being a component.
  CHANGELOG.md
  src/renderer/components/message/Message.tsx
Labels: bug

#3995 Fix the bug where File > Quit on the WebXDC window closes DC
  CHANGELOG.md
  src/main/deltachat/webxdc.ts
  src/main/menu.ts
  src/main/windows/help.ts
  src/main/windows/html_email.ts
  src/main/windows/main.ts
Labels: bug

#3965 feat: add Telegram-style Ctrl+Up shortcut to reply
  CHANGELOG.md
  _locales/_untranslated_en.json
  src/renderer/components/Settings/ExperimentalFeatures.tsx
  src/renderer/components/composer/Composer.tsx
  src/renderer/components/message/MessageListAndComposer.tsx
  src/renderer/keybindings.ts
  src/shared/shared-types.d.ts
  src/shared/state.ts
Labels: experimental feature

#4009 blueprint removal followup
  build/packageignore_list
  electron-builder.json5
  package-lock.json
  scss/manifest.scss
Labels: technical debt

#4011 fix: webxdc: CSP bypass
  CHANGELOG.md
  src/main/deltachat/webxdc.ts
Labels: bug, webxdc

#4040 fix: QR scanning not showing errors on failure
  CHANGELOG.md
  src/renderer/components/QrErrorMessage.tsx
  src/renderer/hooks/useProcessQr.ts
Labels: bug

#4037 fix show new incoming messages after clearing chat
  CHANGELOG.md
  src/renderer/stores/chat/chat_scheduler.ts
  src/renderer/stores/messagelist.ts
Labels: bug

#3980 ImageCropper controls
  CHANGELOG.md
  _locales/_untranslated_en.json
  images/icons/minus.svg
  images/icons/reset-image.svg
  images/icons/rotate-right.svg
  images/icons/swap_hor.svg
  src/renderer/components/Icon/index.tsx
  src/renderer/components/Icon/styles.module.scss
  src/renderer/components/ImageCropper/index.tsx
  src/renderer/components/ImageCropper/styles.module.scss
Labels: enhancement

#4038 fix composite emoji in text avatar, previously it was cut up, for example 🧑‍💻 was shown as just 💻
  CHANGELOG.md
  src/renderer/components/Avatar.tsx
Labels: bug
