Repository deltachat/deltachat-desktop, pull requests merged in 2024-11, with the labels that each got.

#4308 fix missing icons in wallpaper settings
  CHANGELOG.md
  images/icons/image_outline.svg
  images/icons/palette.svg
  packages/frontend/scss/dialogs/_settings.scss
  packages/frontend/src/components/Icon/index.tsx
  packages/frontend/src/components/Icon/styles.module.scss
  packages/frontend/src/components/Settings/Appearance.tsx
Labels: bug

#4316 improvement: rearrange "realtime webxdc" setting
  CHANGELOG.md
  packages/frontend/src/components/Settings/Communication.tsx
  packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
Labels: ui/ux

#4333 improvement: un-experimental Ctrl+Up to reply
  CHANGELOG.md
  _locales/_untranslated_en.json
  docs/KEYBINDINGS.md
  packages/frontend/src/components/KeyboardShortcutHint.tsx
  packages/frontend/src/components/Settings/ExperimentalFeatures.tsx
  packages/frontend/src/components/composer/Composer.tsx
  packages/shared/shared-types.d.ts
  packages/shared/state.ts
Labels: experimental feature

#4224 improvement: arrow-key navigation for chat list
  CHANGELOG.md
  packages/frontend/src/components/chat/ChatList.tsx
  packages/frontend/src/components/chat/ChatListItem.tsx
  packages/frontend/src/contexts/RovingTabindex.tsx
Labels: enhancement, accessibility

#4300 fix borderless drag issues and add debug overlay to better test issues about draging area
  CHANGELOG.md
  packages/frontend/scss/_variables.scss
  packages/frontend/scss/main_screen/_navbar_wrapper.scss
  packages/frontend/scss/misc/_context_menu.scss
  packages/frontend/src/components/Dialog/Dialog.tsx
  packages/frontend/src/components/Dialog/HeaderButton.tsx
  packages/frontend/src/components/Dialog/styles.module.scss
  packages/frontend/src/components/ImageBackdrop/index.tsx
  packages/frontend/src/components/SearchInput/index.tsx
  packages/frontend/src/components/SmallScreenModeMacOSTitleBar.tsx
  packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx
  packages/frontend/src/components/dialogs/CreateChat/index.tsx
  packages/frontend/src/components/dialogs/ForwardMessage/index.tsx
  packages/frontend/src/components/dialogs/MailtoDialog/index.tsx
  packages/frontend/src/components/dialogs/SelectContact/index.tsx
  packages/frontend/src/components/dialogs/WebxdcSendToChat/index.tsx
  packages/frontend/src/components/screens/MainScreen.tsx
  packages/frontend/src/components/screens/NoAccountSelectedScreen/NoAccountSelectedScreen.tsx
  packages/frontend/src/debug-tools.ts
  packages/frontend/src/experimental.ts
Labels: bug, OS: Mac

#4361 fix: arrow-key navigation behavior in search
  CHANGELOG.md
  packages/frontend/src/components/contact/ContactListItem.tsx
  packages/frontend/src/contexts/RovingTabindex.tsx
Labels: bug, accessibility

#4362 improvement: arrow-key navigation in "New Chat"
  CHANGELOG.md
  packages/frontend/src/components/dialogs/CreateChat/index.tsx
  packages/frontend/src/components/helpers/PseudoListItem.tsx
Labels: accessibility
