Repository deltachat/deltachat-desktop, pull requests merged in 2024-09, with the labels that each got.

#4107 Ctrl+Q closes app
  CHANGELOG.md
  src/main/menu.ts
  src/main/tray.ts
  src/main/windows/main.ts
Labels: bug

#4114 fix: spacing around avatars in reaction details dialog
  CHANGELOG.md
  packages/frontend/src/components/dialogs/ReactionsDialog/styles.module.scss
Labels: bug, ui/ux

#4115 Update electron from `30.3.1` to `32.0.2`
  CHANGELOG.md
  packages/target-electron/package.json
  packages/target-electron/src/deltachat/webxdc.ts
  pnpm-lock.yaml
Labels: technical debt
