Repository deltachat/deltachat-desktop, pull requests merged in 2024-01, with the labels that each got.

#3611 fix uncaught exception
  CHANGELOG.md
  src/main/notifications.ts
Labels: bug

#3608 Introduce own React context for context menus & fix regression
  CHANGELOG.md
  src/renderer/App.tsx
  src/renderer/ScreenController.tsx
  src/renderer/components/ContextMenu.tsx
  src/renderer/components/GroupImage.tsx
  src/renderer/components/ThreeDotMenu.tsx
  src/renderer/components/attachment/mediaAttachment.tsx
  src/renderer/components/chat/ChatListContextMenu.tsx
  src/renderer/components/chat/ChatListItem.tsx
  src/renderer/components/dialogs/ChatAuditLogDialog.tsx
  src/renderer/components/dialogs/FullscreenMedia.tsx
  src/renderer/components/dialogs/QrCode.tsx
  src/renderer/components/message/Message.tsx
  src/renderer/contexts/ContextMenuContext.tsx
  src/renderer/contexts/ScreenContext.tsx
  src/renderer/hooks/useContextMenu.ts
Labels: refactor

#3616 message-parse summary text in chatlist item summary
  CHANGELOG.md
  src/renderer/components/chat/ChatListItem.tsx
  src/renderer/components/message/MessageBody.tsx
  src/renderer/components/message/MessageMarkdown.tsx
Labels: enhancement

#3636 move pin icon in chatlist after date
  CHANGELOG.md
  scss/chat/_chat-list-item.scss
  src/renderer/components/chat/ChatListItem.tsx
Labels: ui/ux, polish

#2964 Message reactions with emojis
  CHANGELOG.md
  images/icons/more.svg
  images/icons/reaction.svg
  scss/composer/_emoji-sticker-picker.scss
  scss/message/_message-attachment.scss
  scss/message/_message.scss
  src/renderer/components/AbsolutePositioningHelper/index.tsx
  src/renderer/components/AbsolutePositioningHelper/styles.module.scss
  src/renderer/components/ContactName/index.tsx
  src/renderer/components/ContactName/styles.module.scss
  src/renderer/components/ContextMenu.tsx
  src/renderer/components/EmojiPicker/index.tsx
  src/renderer/components/EmojiPicker/styles.module.scss
  src/renderer/components/Icon/index.tsx
  src/renderer/components/Icon/styles.module.scss
  src/renderer/components/OutsideClickHelper.tsx
  src/renderer/components/Reactions/index.tsx
  src/renderer/components/Reactions/styles.module.scss
  src/renderer/components/ReactionsBar/ReactionsBar.tsx
  src/renderer/components/ReactionsBar/ReactionsBarContext.tsx
  src/renderer/components/ReactionsBar/index.ts
  src/renderer/components/ReactionsBar/styles.module.scss
  src/renderer/components/ReactionsBar/useReactionsBar.ts
  src/renderer/components/ShortcutMenu/index.tsx
  src/renderer/components/ShortcutMenu/styles.module.scss
  src/renderer/components/composer/EmojiAndStickerPicker.tsx
  src/renderer/components/composer/styles.module.scss
  src/renderer/components/contact/Contact.tsx
  src/renderer/components/dialogs/ReactionsDialog/index.tsx
  src/renderer/components/dialogs/ReactionsDialog/styles.module.scss
  src/renderer/components/message/Message.tsx
  src/renderer/components/message/MessageList.tsx
  src/renderer/components/message/MessageListAndComposer.tsx
  src/renderer/components/message/MessageMetaData.tsx
  src/renderer/components/message/MessageWrapper.tsx
  src/renderer/components/message/styles.module.scss
  src/renderer/stores/messagelist.ts
Labels: enhancement
