Repository deltachat/deltachat-desktop, pull requests merged in 2025-01, with the labels that each got.

#4438 improvement: a11y: roving tabindex: End / Home
  CHANGELOG.md
  packages/frontend/src/contexts/RovingTabindex.tsx
Labels: enhancement, ui/ux, accessibility

#4459 add show_app_in_chat option to webxdc info message context menu
  CHANGELOG.md
  packages/frontend/src/components/message/Message.tsx
Labels: enhancement

#4458 fix: devmode: fix logging and counting jsonrpc requests
  CHANGELOG.md
  packages/frontend/src/backend-com.ts
  packages/runtime/runtime.ts
  packages/shared/logger.ts
  packages/target-browser/runtime-browser/runtime.ts
  packages/target-electron/runtime-electron/runtime.ts
Labels: bug

#4441 fix: a11y: arrow-key navigation stopping working after ~10 keypresses
  CHANGELOG.md
  packages/frontend/src/components/Gallery.tsx
  packages/frontend/src/components/chat/ChatList.tsx
  packages/frontend/src/components/dialogs/AddMember/AddMemberInnerDialog.tsx
  packages/frontend/src/components/dialogs/CreateChat/index.tsx
  packages/frontend/src/components/dialogs/SelectChat/index.tsx
  packages/frontend/src/components/dialogs/SelectContact/index.tsx
  packages/frontend/src/components/dialogs/ViewGroup.tsx
  packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Labels: bug, accessibility

#4547 improvement: focus message when jumping to it
  CHANGELOG.md
  packages/frontend/src/components/RuntimeAdapter.tsx
  packages/frontend/src/components/attachment/mediaAttachment.tsx
  packages/frontend/src/components/chat/ChatListItemRow.tsx
  packages/frontend/src/components/composer/Composer.tsx
  packages/frontend/src/components/composer/EmojiAndStickerPicker.tsx
  packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx
  packages/frontend/src/components/dialogs/ForwardMessage/index.tsx
  packages/frontend/src/components/dialogs/FullscreenMedia.tsx
  packages/frontend/src/components/message/Message.tsx
  packages/frontend/src/components/message/MessageList.tsx
  packages/frontend/src/contexts/ChatContext.tsx
  packages/frontend/src/global.d.ts
  packages/frontend/src/hooks/chat/useMessage.ts
  packages/frontend/src/hooks/useVideoChat.ts
  packages/frontend/src/stores/chat/chat_view_reducer.ts
  packages/frontend/src/stores/messagelist.ts
Labels: enhancement, accessibility

#4569 store last account id in core by using selectAccount (which stores it in account manager/accounts.toml)
  CHANGELOG.md
  packages/frontend/src/ScreenController.tsx
  packages/shared/shared-types.d.ts
Labels: technical debt

#4535 refactor: apply `disableWidth` to `<AutoSizer>`s
  packages/frontend/src/components/Gallery.tsx
  packages/frontend/src/components/chat/ChatList.tsx
  packages/frontend/src/components/dialogs/SelectChat/index.tsx
  packages/frontend/src/components/dialogs/ViewGroup.tsx
  packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Labels: refactor

#4551 refactor: rename `useChat().chatWithLinger`
  packages/frontend/src/components/MessageListView.tsx
  packages/frontend/src/components/screens/MainScreen.tsx
  packages/frontend/src/contexts/ChatContext.tsx
  packages/frontend/src/hooks/chat/useChatDialog.ts
Labels: refactor
