Repository deltachat/deltachat-desktop, pull requests merged in 2025-02, with the labels that each got.

#4597 fix: arrow-key nav widgets being unfocusble
  CHANGELOG.md
  packages/frontend/src/components/contact/ContactListItem.tsx
  packages/frontend/src/components/helpers/PseudoListItem.tsx
  packages/frontend/src/contexts/RovingTabindex.tsx
Labels: bug, accessibility

#4610 make log additionally available at "Settings / Advanced / View Log"
  CHANGELOG.md
  packages/frontend/src/components/Settings/Advanced.tsx
Labels: ui/ux

#4533 tauri: implement `runtime.readClipboardImage` and TempFileFunctions, also fix pasting of (non-image) files into composer
  .gitignore
  CHANGELOG.md
  Cargo.lock
  packages/frontend/src/components/QrReader/helper.ts
  packages/frontend/src/components/composer/Composer.tsx
  packages/runtime/runtime.ts
  packages/shared/localize.ts
  packages/target-browser/runtime-browser/runtime.ts
  packages/target-electron/runtime-electron/runtime.ts
  packages/target-electron/src/ipc.ts
  packages/target-tauri/README.md
  packages/target-tauri/runtime-tauri/runtime.ts
  packages/target-tauri/src-tauri/Cargo.toml
  packages/target-tauri/src-tauri/src/clipboard.rs
  packages/target-tauri/src-tauri/src/file_dialogs.rs
  packages/target-tauri/src-tauri/src/help_window.rs
  packages/target-tauri/src-tauri/src/i18n/commands.rs
  packages/target-tauri/src-tauri/src/i18n/errors.rs
  packages/target-tauri/src-tauri/src/i18n/load.rs
  packages/target-tauri/src-tauri/src/i18n/mod.rs
  packages/target-tauri/src-tauri/src/lib.rs
  packages/target-tauri/src-tauri/src/locales.rs
  packages/target-tauri/src-tauri/src/runtime_info.rs
  packages/target-tauri/src-tauri/src/settings.rs
  packages/target-tauri/src-tauri/src/state/app.rs
  packages/target-tauri/src-tauri/src/state/deltachat.rs
  packages/target-tauri/src-tauri/src/temp_file.rs
  packages/target-tauri/src-tauri/tauri.conf.json5
Labels: bug, enhancement

#4637 fix source code links in app picker
  CHANGELOG.md
  packages/frontend/src/components/AppPicker/index.tsx
Labels: bug

#4682 fix missing `maps.xdc` in flatpak build
  CHANGELOG.md
  packages/target-electron/build/afterPackHook.cjs
Labels: bug

#4689 html email view: migrate from deprecated `BrowserView` to `WebContentsView`
  CHANGELOG.md
  packages/target-electron/src/windows/html_email.ts
Labels: technical debt, maintenance

#4697 feat: show "edited" in message status line
  CHANGELOG.md
  packages/frontend/scss/message/_message.scss
  packages/frontend/scss/message/_metadata.scss
  packages/frontend/src/components/message/Message.tsx
  packages/frontend/src/components/message/MessageMetaData.tsx
Labels: new-core, new DC feature
