Repository deltachat/deltachat-desktop, pull requests merged in 2025-09, with the labels that each got.

#5314 test: perf: don't reload page before every test
  packages/e2e-tests/playwright-helper.ts
  packages/e2e-tests/tests/basic-tests.spec.ts
  packages/e2e-tests/tests/group-tests.spec.ts
  packages/e2e-tests/tests/qrcode-tests.spec.ts
  packages/e2e-tests/tests/unencrypted-group-tests.spec.ts
Labels: tests

#5431 test: add tests for chat list multiselect
  packages/e2e-tests/tests/chat-list-multiselect.spec.ts
Labels: tests

#5049 fix: a11y: dont disable composer while sending
  CHANGELOG.md
  packages/frontend/src/components/composer/Composer.tsx
  packages/frontend/src/components/message/MessageListAndComposer.tsx
Labels: bug, accessibility

#5044 fix: a11y: correct `aria-posinset` for chat list
  CHANGELOG.md
  packages/frontend/src/components/chat/ChatListItem.tsx
  packages/frontend/src/components/chat/ChatListItemRow.tsx
  packages/frontend/src/components/contact/ContactListItem.tsx
Labels: accessibility

#5441 test: fix E2E tests
  packages/e2e-tests/tests/chat-list-multiselect.spec.ts
Labels: tests

#5174 tauri: refactor: fix some clippy warnings
  packages/target-tauri/crates/user-notify/examples/test.rs
  packages/target-tauri/src-tauri/build.rs
  packages/target-tauri/src-tauri/src/blobs.rs
  packages/target-tauri/src-tauri/src/html_window/email_scheme.rs
  packages/target-tauri/src-tauri/src/lib.rs
  packages/target-tauri/src-tauri/src/menus/mod.rs
  packages/target-tauri/src-tauri/src/state/tray_manager.rs
  packages/target-tauri/src-tauri/src/state/webxdc_instances.rs
  packages/target-tauri/src-tauri/src/temp_file.rs
  packages/target-tauri/src-tauri/src/themes/themes.rs
  packages/target-tauri/src-tauri/src/util/fs_watcher.rs
  packages/target-tauri/src-tauri/src/util/truncate_text.rs
  packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
  packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
Labels: refactor, Runtime: Tauri

#5125 fix: a11y: focus being locked on message input
  CHANGELOG.md
  packages/frontend/src/components/message/MessageListAndComposer.tsx
Labels: bug, accessibility

#5435 test: add another chat multiselect test
  packages/e2e-tests/tests/chat-list-multiselect.spec.ts
Labels: tests

#5442 fix: a11y: delivery status being announced twice
  CHANGELOG.md
  packages/e2e-tests/tests/unencrypted-group-tests.spec.ts
  packages/frontend/scss/message/_message.scss
  packages/frontend/scss/message/_metadata.scss
  packages/frontend/src/components/message/MessageMetaData.tsx
Labels: accessibility

#5457 improvement: adjust notif settings appearance
  packages/frontend/src/components/Settings/Notifications.tsx
Labels: ui/ux

#5473 fix: emit core events on main proc JSON-RPC client
  packages/target-electron/src/deltachat/controller.ts
Labels: refactor, Runtime: Electron

#5474 refactor: update copy-pasted browser JSON-RPC code
  packages/target-browser/src/deltachat-rpc.ts
Labels: refactor, Runtime: Browser

#5484 fix: hide "Start call" button when unavailable
  packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Labels: bug, experimental feature

#5486 feat: show caller's name on incoming call
  packages/target-electron/src/windows/video-call.ts
Labels: enhancement, experimental feature

#5488 improvement: calls: use in-app "Answer?" prompt
  packages/target-electron/src/windows/video-call.ts
  packages/target-electron/static/calls-webapp-preload.js
  pnpm-lock.yaml
Labels: enhancement, experimental feature

#5490 fix: calls window: a way to go fullscreen, zoom
  packages/target-electron/src/windows/video-call.ts
Labels: enhancement, experimental feature

#5494 Improvements to Dialog Bottom Margin
  CHANGELOG.md
  packages/frontend/src/components/Dialog/styles.module.scss
  packages/frontend/src/components/Settings/Settings.tsx
  packages/frontend/src/components/Settings/SettingsSeparator.tsx
  packages/frontend/src/components/Settings/styles.module.scss
  packages/frontend/src/components/dialogs/About.tsx
  packages/frontend/src/components/dialogs/MediaView/styles.module.scss
  packages/frontend/src/components/screens/WelcomeScreen/AlternativeSetupsDialog.tsx
  packages/frontend/src/components/screens/WelcomeScreen/OnboardingScreen.tsx
  packages/frontend/src/components/screens/WelcomeScreen/UseOtherServerDialog.tsx
Labels: ui/ux, polish
