Repository deltachat/deltachat-desktop, pull requests merged in 2025-07, with the labels that each got.

#5251 test: bump test timeout from 30s to 5m
  packages/e2e-tests/playwright.config.ts
Labels: tests

#5203 fix: minor fixes for `ProxyConfiguration`
  packages/frontend/src/components/dialogs/ProxyConfiguration/index.tsx
Labels: bug, refactor

#5204 fix: set "unread" count to 0 when jump to bottom
  CHANGELOG.md
  packages/frontend/src/components/message/MessageList.tsx
Labels: bug

#5244 fix: not marking last info message as read
  CHANGELOG.md
  packages/frontend/scss/message/_message.scss
Labels: bug, ui/ux

#5273 Slightly increase contrast for unread badge on pinned muted chats.
  CHANGELOG.md
  packages/frontend/themes/_themebase.scss
Labels: ui/ux

#5237 perf: one `getFullChatById` -> `getBasicChatInfo`
  CHANGELOG.md
  packages/frontend/src/backend/group.ts
Labels: performance

#5230 perf: reduce debouncing in `useContactIds`
  CHANGELOG.md
  packages/frontend/package.json
  packages/frontend/src/components/contact/ContactList.tsx
  packages/frontend/src/components/dialogs/AddMember/AddMemberDialog.tsx
  packages/frontend/src/components/dialogs/CreateChat/index.tsx
  pnpm-lock.yaml
Labels: technical debt, performance

#5232 perf: use asyncThrottle in useChatList
  CHANGELOG.md
  packages/frontend/src/components/chat/ChatListHelpers.tsx
Labels: refactor, technical debt, performance

#5278 fix: style: distance between account list items
  packages/frontend/src/components/AccountListSidebar/styles.module.scss
Labels: ui/ux, accessibility

#5267 perf: improve ChatList performance, refactor a little
  packages/frontend/src/components/chat/ChatList.tsx
Labels: refactor, performance

#5275 refactor: improve type safety of `ChatListPart`, other minor stuff
  packages/frontend/src/components/chat/ChatList.tsx
Labels: refactor

#5292 prevent navigation when clicking on email addresses
  packages/frontend/src/components/message/MessageMarkdown.tsx
Labels: bug

#5295 donation device message
  CHANGELOG.md
  packages/frontend/src/stockStrings.ts
Labels: new-core

#5306 tauri: fix: deny more webxdc permissions
  packages/target-tauri/src-tauri/src/webxdc/webxdc_scheme.rs
Labels: Runtime: Tauri

#5315 chore: fix Tauri Ubuntu build: upgrade Tauri CLI
  packages/target-tauri/package.json
  pnpm-lock.yaml
Labels: build, Runtime: Tauri

#5312 test: fix qrcode test not deleting all profiles
  packages/e2e-tests/tests/qrcode-tests.spec.ts
Labels: tests

#5350 improvement: add more margin for daymarker msgs
  packages/frontend/scss/message/_message.scss
Labels: ui/ux
