Repository deltachat/deltachat-desktop, pull requests merged in 2025-06, with the labels that each got.

#5182 tauri: prevent moving around of the whole app with the touchpad gestures on windows
  CHANGELOG.md
  packages/frontend/scss/_global.scss
Labels: bug, OS: Windows, Runtime: Tauri

#5187 fix: "Copy Selected Text" on message not working
  CHANGELOG.md
  packages/frontend/src/components/message/Message.tsx
Labels: bug

#5189 fix: a11y: fix incorrect gallery "tab" role
  CHANGELOG.md
  packages/frontend/src/components/Gallery.tsx
  packages/frontend/src/components/NoChatSelected.tsx
  packages/frontend/src/components/message/MessageListAndComposer.tsx
  packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Labels: accessibility

#5194 fix: notifications not working sometimes
  CHANGELOG.md
  packages/frontend/src/system-integration/notifications.ts
Labels: bug, blocker

#5196 fix: dropping files on Windows
  CHANGELOG.md
  packages/frontend/src/components/message/MessageListAndComposer.tsx
Labels: bug, blocker, OS: Windows, Runtime: Electron, Runtime: Tauri

#5181 tauri: fix: remember webxdc window position & size
  CHANGELOG.md
  Cargo.lock
  packages/target-tauri/src-tauri/Cargo.toml
  packages/target-tauri/src-tauri/src/lib.rs
  packages/target-tauri/src-tauri/src/webxdc/commands_main_window.rs
Labels: webxdc, Runtime: Tauri
