Repository deltachat/deltachat-desktop, pull requests merged in 2025-08, with the labels that each got.

#5373 fix: hide fullscreen avatar view for unencrypted
  CHANGELOG.md
  packages/frontend/src/components/Avatar/index.tsx
  packages/frontend/src/components/ImageSelector/index.tsx
  packages/frontend/src/components/LargeProfileImage/index.tsx
  packages/frontend/src/components/ProfileInfoHeader/index.tsx
  packages/frontend/src/components/Settings/Profile.tsx
  packages/frontend/src/components/dialogs/MailingListProfile.tsx
  packages/frontend/src/components/dialogs/ViewGroup.tsx
  packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Labels: ui/ux, catching up with other clients

#5374 fix: hide "fullscreen avatar" for Saved Messages
  packages/frontend/src/components/dialogs/ViewProfile/index.tsx
Labels: ui/ux

#5376 fix: a11y: focus "React" menu on open
  CHANGELOG.md
  packages/frontend/src/components/ReactionsBar/ReactionsBar.tsx
Labels: accessibility

#5347 improvement: a11y: add `aria-label` for some menus
  CHANGELOG.md
  _locales/_untranslated_en.json
  packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
  packages/frontend/src/components/ContextMenu.tsx
  packages/frontend/src/components/ThreeDotMenu.tsx
  packages/frontend/src/components/chat/ChatListContextMenu.tsx
  packages/frontend/src/components/composer/menuAttachment.tsx
  packages/frontend/src/components/message/Message.tsx
  packages/frontend/src/hooks/useContextMenu.ts
Labels: accessibility

#5345 improvement: a11y: aria-haspopup=menu contextMenu
  CHANGELOG.md
  packages/frontend/src/components/AccountListSidebar/AccountItem.tsx
  packages/frontend/src/components/attachment/mediaAttachment.tsx
  packages/frontend/src/components/chat/ChatListItem.tsx
  packages/frontend/src/components/contact/ContactListItem.tsx
  packages/frontend/src/components/dialogs/ChatAuditLogDialog.tsx
  packages/frontend/src/components/dialogs/FullscreenAvatar.tsx
  packages/frontend/src/components/dialogs/FullscreenMedia.tsx
  packages/frontend/src/components/dialogs/QrCode.tsx
  packages/frontend/src/components/message/Link.tsx
  packages/frontend/src/components/message/Message.tsx
Labels: accessibility

#5355 improvement: a11y: remove "dialog" role from menu
  CHANGELOG.md
  packages/frontend/src/components/ContextMenu.tsx
Labels: accessibility

#5412 Remove unused variables in themebase
  packages/frontend/themes/_themebase.scss
  packages/frontend/themes/dark_amoled.scss
  packages/frontend/themes/darkpurple.scss
  packages/frontend/themes/dev_minimal.scss
  packages/frontend/themes/dev_rocket.scss
  packages/frontend/themes/light.scss
Labels: technical debt

#5283 refactor: fix potential ChatListItem `memo()` bugs
  packages/frontend/src/components/chat/ChatListItem.tsx
  packages/frontend/src/components/chat/ChatListItemRow.tsx
  packages/frontend/src/components/screens/MainScreen/MainScreen.tsx
Labels: refactor
